apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: comp-2048-lebo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: comp-2048-lebo
    app.kubernetes.io/part-of: sho-2048
  name: comp-2048-lebo
  namespace: showeimer-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: comp-2048-lebo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: comp-2048-lebo
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:9975edfd068b9bc539acd8126e6ea826e3da1e0db3b186726c1d5ad7cd160ecb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
