apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: a2048-ykfv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: a2048-ykfv
    app.kubernetes.io/part-of: sho-2048
  name: a2048-ykfv
  namespace: showeimer-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: a2048-ykfv
    weight: null
status: {}
