apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: a2048-ykfv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: a2048-ykfv
    app.kubernetes.io/part-of: sho-2048
  name: a2048-ykfv
  namespace: showeimer-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: a2048-ykfv
status:
  loadBalancer: {}
